const express = require('express');
const { userWelcome, signUp, signIn, dashBoard, product, productid, investnow, changepassword, profile, emailpage, forgetpassword, fundaccount, getHistory, investperform, Adminlogin, Admindb, getall, putall, postall, delecteach, getuseranimalinvest, totalbalance, totalAmountInvested, Totalinvest, changePasswordAdmin, createplan, getuserplans, adminplansdelect, updateplan, getplan, planinvestnow, adnotification, getusernotification, fetchUsersNotifications, likeplan,} = require('../Controllers/user.controllers');
const router = express.Router()


router.get("/user", userWelcome);
router.post("/signup", signUp)
router.post("/signin", signIn)
router.get("/dashboard", dashBoard)
router.get("/product", product)
router.get("/productid/:id", productid)
router.post("/investnow", investnow)
router.post("/changepassword", changepassword)
router.post("/profile", profile)
router.post("/emailpage", emailpage)
router.post("/forgetpass", forgetpassword)
router.post("/fundaccount", fundaccount)
router.post("/getHistory", getHistory)
router.get("/investperform", investperform)
router.post("/adminlogin", Adminlogin)
router.get("/Admindb", Admindb)
router.get("/getallusers", getall)
router.put("/putall/:id", putall)
router.post("/postall", postall)
router.delete("/delecteachuser/:id", delecteach)
router.get("/getuseranimalinvest", getuseranimalinvest)
router.get("/totalbalance", totalbalance)
router.get("/totalAmountInvested", totalAmountInvested)
router.get("/Totalinvest", Totalinvest)
router.post("/changePasswordAdmin", changePasswordAdmin)
router.post("/createplan", createplan)
router.get("/getuserplans", getuserplans)
router.delete("/adminplansdelect/:id", adminplansdelect)
router.put("/updateplan/:id", updateplan)
router.get("/getplan/:id", getplan)
router.post("/planinvestnow", planinvestnow)
router.post("/adnotification", adnotification)
router.get("/getusernotification", getusernotification)
router.get("/fetchUsersNotifications", fetchUsersNotifications)
router.post("/likeplan", likeplan)
module.exports = router